version: '3.7'

services:
  nginx:
    image: nginx:1.15.3-alpine
    restart: on-failure
    volumes:
      - './apps/lama_game/public/:/usr/src/app'
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
    ports:
      - "80:80"
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    restart: on-failure
    env_file:
      - .env
    user: 1000:1000